### ISSUE TITLE
Bulk update

### ISSUE THREAD

**Issue by slxl** [Karetski/Snowonder#23]
hi! thanks for a tool, I looked a replacement for format tools since 3rd party plugins were removed from Xcode.

but the question is there a chance to make it able to process all project files and format every .h/.m file at once?

thanks!

**Comment by Karetski** [comment]
Hey @slxl ! It's impossible to implement described functionality as part of Xcode Extension since XcodeKit doesn't give access for the whole list of files in project but only for currently opened XCSourceTextBuffer.

I plan to create CLI that will allow to implement described functionality, but there are few things to do previously. So I need some more time.
